version: '3'

volumes:
  postgresql-migrate-volume:


services:
  postgresql:
    image: postgres:latest
    container_name: postgres-ex1
    volumes:
      - postgresql-migrate-volume:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
